Repository clique-orbital/clique2, pull requests merged in 2019-07, with the labels that each got.

#22 Add User Guide link in README
  README.md
Labels: documentation

#25 Update DeveloperGuide.md
  DeveloperGuide.md
Labels: documentation

#51 Poll Feature (complete)
  App.js
  functions/index.js
  ios/RNFirebaseStarter.xcodeproj/project.pbxproj
  src/assets/theme.js
  src/components/ContactsList.js
  src/components/Input.js
  src/components/LoadingView.js
  src/components/PollMessageBubble.js
  src/components/PollModal.js
  src/components/Spinner.js
  src/components/SystemMessageBubble.js
  src/screens/Auth/Auth.js
  src/screens/Auth/UserDetails.js
  src/screens/Main/GroupScreen.js
  src/screens/Main/GroupScreenStack.js
  src/screens/Main/Groups/ChatScreen.js
  src/screens/Main/Groups/CreateEvents.js
  src/screens/Main/Groups/CreatePoll.js
  src/screens/Main/Groups/GroupDetails.js
  src/screens/Main/SettingsScreen.js
  src/store/actions/groups.js
  src/store/actions/pollModal.js
  src/store/configureStore.js
  src/store/constants.js
  src/store/reducers/pollModalReducer.js
Labels: enhancement

#59 Notifications (complete)
  .firebaserc
  App.js
  functions/index.js
  functions/package-lock.json
  package-lock.json
  package.json
  src/screens/Auth/Auth.js
  src/screens/Auth/AuthLoading.js
  src/screens/Main/GroupScreen.js
  src/screens/Main/Groups/ChatScreen.js
  src/screens/Main/NotificationsScreen.js
  src/store/actions/messages.js
  src/store/constants.js
  src/store/reducers/messagesReducer.js
Labels: enhancement

#60 Dark mode everything except tab bar
  App.js
  src/assets/theme.js
  src/components/CalendarComponent.js
  src/components/ContactsList.js
  src/components/ContinueButton.js
  src/components/EventBubble.js
  src/components/MessageBubble.js
  src/components/MyCheckbox.js
  src/components/PollMessageBubble.js
  src/components/PollModal.js
  src/components/SystemMessageBubble.js
  src/screens/Main/EventModal.js
  src/screens/Main/GroupScreen.js
  src/screens/Main/GroupScreenStack.js
  src/screens/Main/Groups/AddMembers.js
  src/screens/Main/Groups/CalendarScreen.js
  src/screens/Main/Groups/ChatScreen.js
  src/screens/Main/Groups/CreateEvents.js
  src/screens/Main/Groups/CreateGroups.js
  src/screens/Main/Groups/GroupDetails.js
  src/screens/Main/Groups/GroupInformation.js
  src/screens/Main/NotificationsScreen.js
  src/screens/Main/PersonalCalendar.js
  src/screens/Main/SettingsScreen.js
  src/store/actions/theme.js
  src/store/constants.js
  src/store/reducers/index.js
  src/store/reducers/themeReducer.js
Labels: enhancement

#61 Fix Header and Tab bar dark mode
  App.js
  android/hs_err_pid63349.log
  src/assets/theme.js
  src/components/ButtonsModal.js
  src/components/CalendarComponent.js
  src/components/MyHeader.js
  src/components/PollModal.js
  src/components/TabBarComponent.js
  src/screens/Main/CalendarStack.js
  src/screens/Main/EventModal.js
  src/screens/Main/GroupScreen.js
  src/screens/Main/GroupScreenStack.js
  src/screens/Main/Groups/AddMembers.js
  src/screens/Main/Groups/CalendarScreen.js
  src/screens/Main/Groups/ChatScreen.js
  src/screens/Main/Groups/CreateEvents.js
  src/screens/Main/Groups/CreateGroups.js
  src/screens/Main/Groups/CreatePoll.js
  src/screens/Main/Groups/GroupDetails.js
  src/screens/Main/Groups/GroupInformation.js
  src/screens/Main/PersonalCalendar.js
  src/screens/Main/SettingsScreen.js
  src/store/reducers/messagesReducer.js
  src/store/reducers/pollModalReducer.js
Labels: enhancement

#62 Fix validation for editing group details
  src/assets/theme.js
  src/components/Spinner.js
  src/screens/Auth/UserDetails.js
  src/screens/Main/Groups/CreatePoll.js
  src/screens/Main/Groups/GroupDetails.js
Labels: bug, invalid
